// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cntiunpervwsmyrvnaxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudGl1bnBlcnZ3c215cnZuYXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODQ0MzksImV4cCI6MjA3MzM2MDQzOX0.xmvvxeKmfdLSx01vIh90h2Lo_s2WojarUtheBzKHGj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});